version: '3.1'

services:
  postgres:
    image: postgres:13.3
    container_name: postgressdb
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: 18175118N
      POSTGRES_DB: SteamApi

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmindb
    environment:
      PGADMIN_DEFAULT_EMAIL: 220240@fppiramide.com
      PGADMIN_DEFAULT_PASSWORD: 18175118N
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  db_data:
  database_sql:
